import { IconArrowUpRight, IconClock, IconMail, IconMapPin, IconPhone } from "@tabler/icons-react";
import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";
import ContactForm from "@/components/sections/ContactForm";
import DetailHero from "@/components/sections/DetailHero";
import { siteConfig } from "@/data/site-content";

export default function ContactPage() {
  return <><Header /><main id="main-content"><DetailHero eyebrow="Concierge desk" breadcrumb="Contact" title="Let’s make a clear route forward." description="Tell us what you are moving, where it is registered and what you need next. Our maritime team will come back with the right route and documents." image="/images/foreign-yacht.png" imageAlt="Sailing yacht arriving in Dubai coastal waters" /><section className="relative py-20 sm:py-24"><div className="mx-auto grid max-w-7xl gap-4 px-5 sm:px-6 md:grid-cols-3 lg:px-8">{[[IconPhone, "Call directly", siteConfig.phone, `tel:${siteConfig.phone.replace(/\s/g, "")}`], [IconMail, "Write to us", siteConfig.email, `mailto:${siteConfig.email}`], [IconMapPin, "Visit us", siteConfig.address, undefined]].map(([Icon, label, value, href]) => { const DetailIcon = Icon as typeof IconPhone; return <div key={String(label)} className="rounded-2xl border border-white/[.08] bg-navy-900/45 p-5"><DetailIcon size={20} className="text-cyan-accent"/><p className="mt-6 text-[10px] font-bold uppercase tracking-[.18em] text-white/40">{String(label)}</p>{href ? <a href={String(href)} className="mt-2 block text-sm font-semibold text-white transition hover:text-cyan-accent">{String(value)}</a> : <p className="mt-2 text-sm font-semibold text-white">{String(value)}</p>}</div>})}</div></section><ContactForm /><section className="pb-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-6 rounded-2xl border border-white/[.08] bg-white/[.035] p-6 sm:flex-row sm:items-center sm:p-8"><div className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-cyan-accent/10 text-cyan-accent"><IconClock size={20}/></span><div><p className="font-semibold text-white">A practical first conversation</p><p className="mt-1 text-sm text-white/50">Share the basics and we’ll help identify the next step.</p></div></div><a href={`mailto:${siteConfig.email}`} className="inline-flex items-center gap-2 text-sm font-bold text-cyan-accent hover:text-white">Email the desk <IconArrowUpRight size={17}/></a></div></div></section></main><Footer /></>;
}
