"use client";
import { useState } from "react";
import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";
import DetailHero from "@/components/sections/DetailHero";
import Image from "next/image";
const images = [["/images/marine-hero.png", "Yachts", "Luxury yacht on open water"], ["/images/commercial-vessel.png", "Commercial", "Commercial vessel underway"], ["/images/foreign-yacht.png", "Yachts", "Foreign yacht in UAE waters"], ["/images/naval-survey.png", "Technical", "Naval survey documentation"], ["/images/marine-experts.png", "Technical", "Marine experts at work"], ["/images/marine-hero.png", "Commercial", "Marine operations on open water"]] as const;
const categories = ["All", "Yachts", "Commercial", "Technical"] as const;
export default function Gallery() { const [active, setActive] = useState<(typeof categories)[number]>("All"); const visible = active === "All" ? images : images.filter(([, category]) => category === active); return <><Header/><main id="main-content"><DetailHero eyebrow="Gallery" breadcrumb="Gallery" title="A closer look at work on the water." description="A visual introduction to the vessels, technical work and people behind Marine Registration Services." image="/images/marine-hero.png" imageAlt="Luxury yacht cruising on open water"/><section className="mx-auto max-w-7xl px-5 py-20 sm:py-28"><div className="flex flex-wrap gap-3">{categories.map(category => <button key={category} onClick={() => setActive(category)} aria-pressed={active === category} className={`rounded-full px-3 py-2 text-xs font-bold uppercase tracking-widest transition ${active === category ? "bg-cyan-accent text-navy-950" : "text-cyan-accent hover:bg-white/10"}`}>{category}</button>)}</div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.map(([src, category, alt], i) => <figure key={`${src}-${category}-${i}`} className="relative aspect-[4/3] overflow-hidden rounded-2xl border border-white/10"><Image src={src} alt={alt} fill className="object-cover transition duration-500 hover:scale-105" sizes="(max-width: 768px) 100vw, 33vw"/><figcaption className="absolute inset-x-0 bottom-0 bg-navy-950/70 px-4 py-3 text-xs text-white">{category}</figcaption></figure>)}</div></section></main><Footer/></>; }
